/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.Venda.RelatorioVenda;
import view.Venda.FormularioVenda;
import view.Veiculo.FormularioVeiculo;
import view.Veiculo.RelatorioVeiculo;
import view.Funcionario.RelatorioFuncionario;
import view.Funcionario.FormularioFuncionario;
import view.Cliente.RelatorioCliente;
import view.Cliente.FormularioCliente;
import controller.Concessionaria;

/**
 *
 * @author hiago
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private final Concessionaria controller;
    private final FormularioCliente formularioCliente;
    private final RelatorioCliente relatorioCliente;
    private final FormularioFuncionario formularioFuncionario;
    private final RelatorioFuncionario relatorioFuncionario;
    private final FormularioVeiculo formularioVeiculo;
    private final RelatorioVeiculo relatorioVeiculo;
    private final FormularioVenda formularioVenda;
    private final RelatorioVenda relatorioVenda;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        this.controller = new Concessionaria();
        this.relatorioCliente = new RelatorioCliente(this.controller);
        this.formularioCliente = new FormularioCliente(this.controller, this.relatorioCliente);
        this.formularioFuncionario = new FormularioFuncionario(this.controller);
        this.relatorioFuncionario = new RelatorioFuncionario(this.controller);
        this.formularioVeiculo = new FormularioVeiculo(this.controller);
        this.relatorioVeiculo = new RelatorioVeiculo(this.controller);
        this.formularioVenda = new FormularioVenda(this.controller);
        this.relatorioVenda = new RelatorioVenda(this.controller);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        gerCliente = new javax.swing.JButton();
        gerFuncionario = new javax.swing.JButton();
        gerVeiculo = new javax.swing.JButton();
        gerVendas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Concessionária Dantas");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gerCliente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        gerCliente.setText("Gerenciar Clientes");
        gerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerClienteActionPerformed(evt);
            }
        });

        gerFuncionario.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        gerFuncionario.setText("Gerenciar Funcionários");
        gerFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerFuncionarioActionPerformed(evt);
            }
        });

        gerVeiculo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        gerVeiculo.setText("Gerenciar Veículos");
        gerVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerVeiculoActionPerformed(evt);
            }
        });

        gerVendas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        gerVendas.setText("Gerenciar Vendas");
        gerVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerVendas)
                    .addComponent(gerVeiculo)
                    .addComponent(gerFuncionario)
                    .addComponent(gerCliente)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerCliente)
                .addGap(18, 18, 18)
                .addComponent(gerFuncionario)
                .addGap(18, 18, 18)
                .addComponent(gerVeiculo)
                .addGap(18, 18, 18)
                .addComponent(gerVendas)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerClienteActionPerformed
        this.formularioCliente.setVisible(true);
    }//GEN-LAST:event_gerClienteActionPerformed

    private void gerFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerFuncionarioActionPerformed
        this.formularioFuncionario.setVisible(true);
    }//GEN-LAST:event_gerFuncionarioActionPerformed

    private void gerVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerVeiculoActionPerformed
        this.formularioVeiculo.setVisible(true);
    }//GEN-LAST:event_gerVeiculoActionPerformed

    private void gerVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerVendasActionPerformed
        this.formularioVenda.setVisible(true);
    }//GEN-LAST:event_gerVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerCliente;
    private javax.swing.JButton gerFuncionario;
    private javax.swing.JButton gerVeiculo;
    private javax.swing.JButton gerVendas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
